---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "mssql-configmap"
  namespace: "default"
  labels:
    app: "mssql"
data:
  ACCEPT_EULA: "Y"
  MSSQL_SA_PASSWORD: "Password123"
  MSSQL_PID: "Evaluation"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "mssql"
  namespace: "default"
  labels:
    app: "mssql"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "mssql"
  template:
    metadata:
      labels:
        app: "mssql"
    spec:
      containers:
      - name: "server-1"
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        env:
        - name: "ACCEPT_EULA"
          valueFrom:
            configMapKeyRef:
              key: "ACCEPT_EULA"
              name: "mssql-configmap"
        - name: "MSSQL_SA_PASSWORD"
          valueFrom:
            configMapKeyRef:
              key: "MSSQL_SA_PASSWORD"
              name: "mssql-configmap"
        - name: "MSSQL_PID"
          valueFrom:
            configMapKeyRef:
              key: "MSSQL_PID"
              name: "mssql-configmap"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "mssql-service"
  namespace: "default"
  labels:
    app: "mssql"
spec:
  ports:
  - protocol: "TCP"
    port: 1433
    targetPort: 1433
  selector:
    app: "mssql"
  type: "LoadBalancer"
  loadBalancerIP: ""
